## Syed Sajjad Askai

### 2139484

## Lab Program 1(Section -1 and Section -2)


In [1]:
import os
import matplotlib.pyplot as plt
##to save the file 
import joblib
import numpy as np
import pandas as pd

plt.style.use("fivethirtyeight")


In [2]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int = None):
        ## to keep the weight smalll #here 1e-4 is 10 to the power of 4  i.e 0.00001
        self.weights = np.random.randn(3) * 1e-4
        ##Learing rate
        self.eta = eta
        ##iteration
        self.epochs = epochs
        
        ## Fardward pass
        ##Matrix Multiplication
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    ## define Activation Function()
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
        
        ## X and Y is dependent and independent variable
    def fit(self, X, y):
        self.X = X
        self.y = y

        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n {X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch + 1}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
    
            
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
    

In [3]:
AND = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,0,0,1]
}

df_And = pd.DataFrame(AND)

In [4]:
## Prepare the data
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return X, y

In [5]:
X, y = prepare_data(df_And)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [6]:
ETA = 1
EPOCHS = 5
model_And = Perceptron(eta= ETA, epochs = EPOCHS)

model_And.fit(X, y)

X with bias: 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 1 0]
error: 
0    0
1    0
2   -1
3    1
Name: y, dtype: int64
updated weights after epoch: 1/5: 
[7.96467106e-05 9.99933993e-01 5.88619401e-05]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 2/5: 
[-9.99920353e-01 -6.60065328e-05  2.00005886e+00]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 3/5: 
[7.96467106e-05 9.99933993e-01 1.00005886e+00]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0


In [7]:
model_And.predict(X)

array([0, 0, 0, 0])

In [8]:
XOR_Gate = {
    "x1" :[0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,0]
}
df_And = pd.DataFrame(XOR_Gate)

In [9]:
X, y = prepare_data(df_And)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [10]:
ETA = 1
EPOCHS = 5
model_And = Perceptron(eta= ETA, epochs = EPOCHS)

model_And.fit(X, y)

X with bias: 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[1 0 0 0]
error: 
0   -1
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/5: 
[ 0.99994086  0.99989609 -1.00003893]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 2/5: 
[-5.91405620e-05 -1.03909603e-04  9.99961072e-01]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 3/5: 
[ 0.99994086  0.99989609 -1.00003893]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name