In [1]:
    #import os
    #os.chdir("../")
    #os.getcwd()

In [2]:
import warnings
import tensorflow as tf
from tensorflow import keras
from keras.datasets import mnist
from keras.layers import Dense, Flatten, Conv2D, AveragePooling2D
from keras.models import Sequential


2023-01-10 19:16:36.021370: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-10 19:16:36.168786: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-01-10 19:16:36.168833: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-01-10 19:16:37.186516: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

In [3]:
(X_train, y_train),(X_test, y_test) = mnist.load_data()

In [4]:
X_train.shape
#60000 images of 28*28 black 

(60000, 28, 28)

In [5]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [6]:
#preforming the reshape
X_train = X_train.reshape(X_train.shape[0],28,28,1) #Add the channnel 1
X_test = X_test.reshape(X_test.shape[0],28,28,1)

In [7]:
X_train.shape

(60000, 28, 28, 1)

In [8]:
#Normalization 
X_train = X_train / 255
X_test = X_test / 255

In [9]:
y_train[0]

5

In [10]:
#converting it into one hot encoding [0,0,0,0,0,1,0,0,0]
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [11]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

# Model Architucture 


LabAssignment/Screenshot 2023-01-10 at 7.22.55 PM.png

In [12]:
model = Sequential()#Sequential groups a linear stack of layers
model.add(Conv2D(6,kernel_size=(5,5), padding = 'valid', activation='tanh', input_shape=(28,28,1))) #given in research paper of nenet-5
model.add(AveragePooling2D(pool_size=(2,2), strides = 2, padding='valid'))
model.add(Conv2D(16,kernel_size=(5,5), padding = 'valid', activation='tanh')) #given in research paper
model.add(AveragePooling2D(pool_size=(2,2), strides = 2, padding='valid'))
model.add(Flatten())#Flattens the input. Does not affect the batch size
model.add(Dense(120, activation='tanh'))
model.add(Dense(84, activation='tanh'))
model.add(Dense(10, activation='softmax'))
model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d (AverageP  (None, 12, 12, 6)        0         
 ooling2D)                                                       
                                                                 
 conv2d_1 (Conv2D)           (None, 8, 8, 16)          2416      
                                                                 
 average_pooling2d_1 (Averag  (None, 4, 4, 16)         0         
 ePooling2D)                                                     
                                                                 
 flatten (Flatten)           (None, 256)               0         
                                                                 
 dense (Dense)               (None, 120)               3

2023-01-10 19:16:40.790872: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-01-10 19:16:40.791036: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-01-10 19:16:40.791060: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ec59d7d16be4): /proc/driver/nvidia/version does not exist
2023-01-10 19:16:40.791305: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [13]:
model.compile(loss = keras.metrics.categorical_crossentropy, optimizer = keras.optimizers.Adam(), metrics = ['Accuracy'])

In [14]:
model.fit(X_train, y_train, batch_size=120, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
500/500 [==============================] - 7s 11ms/step - loss: 0.3375 - Accuracy: 0.9037 - val_loss: 0.1456 - val_Accuracy: 0.9574
Epoch 2/10
500/500 [==============================] - 5s 10ms/step - loss: 0.1215 - Accuracy: 0.9631 - val_loss: 0.0876 - val_Accuracy: 0.9740
Epoch 3/10
500/500 [==============================] - 5s 10ms/step - loss: 0.0810 - Accuracy: 0.9756 - val_loss: 0.0726 - val_Accuracy: 0.9758
Epoch 4/10
500/500 [==============================] - 5s 10ms/step - loss: 0.0611 - Accuracy: 0.9815 - val_loss: 0.0588 - val_Accuracy: 0.9810
Epoch 5/10
500/500 [==============================] - 5s 10ms/step - loss: 0.0492 - Accuracy: 0.9844 - val_loss: 0.0500 - val_Accuracy: 0.9835
Epoch 6/10
500/500 [==============================] - 5s 10ms/step - loss: 0.0409 - Accuracy: 0.9871 - val_loss: 0.0484 - val_Accuracy: 0.9844
Epoch 7/10
500/500 [==============================] - 5s 10ms/step - loss: 0.0344 - Accuracy: 0.9890 - val_loss: 0.0450 - val_Accuracy: 0.9836

In [19]:
60000 / 120

500.0

In [20]:
score = model.evaluate(X_test, y_test)

print("Test loss",score[0])
print("test Accuracy" , score[1])

313/313 [==============================] - 1s 3ms/step - loss: 0.0414 - Accuracy: 0.9854
Test loss 0.041355155408382416
test Accuracy 0.9854000210762024
