In [4]:
import os
import matplotlib.pyplot as plt
##to save the file 
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [8]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int = None):
        ## to keep the weight smalll #here 1e-4 is 10 to the power of 4  i.e 0.00001
        self.weights = np.random.randn(3) * 1e-4
        ##Learing rate
        self.eta = eta
        ##iteration
        self.epochs = epochs
        
    def fit(Self, X, y):## X and Y is dependent and independent variable
        self.X = X
        self.y = y
        
        X_with_bais = np.c_[self.X, -np.ones(len(self.X),1)]##Adding bais  -1 
        print(f"X with bais:\n {X_with_bais}")
        
    

In [9]:
obj = Perceptron(eta = 0.01, epochs = 10)

In [11]:
obj.epochs

10

In [12]:
obj.weights

array([-3.95415875e-05, -8.86982118e-05,  1.97329848e-05])

In [18]:
X = -np.ones((4,1))
y = np.ones(4)
print(X)
print(y)

[[-1.]
 [-1.]
 [-1.]
 [-1.]]
[1. 1. 1. 1.]


In [13]:
obj.fit(X, y)

NameError: name 'X' is not defined